version: '3.3'
services:

# -------------------------------------------
# NODE STACK (add analytical modules here)
# -------------------------------------------
  node1:
    image: qunis/ahub_rnode:2.0

# -------------------------------------------
  node2:
    image: qunis/ahub_rnode:2.0

# -------------------------------------------
  node3:
    image: qunis/prophetdemo
    
# -------------------------------------------

# -------------------------------------------
# SERVICE STACK (DO NOT TOUCH)
# -------------------------------------------

  boss:
    image: qunis/ahub_boss:2.0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    configs:
      - source: main_config
        target: /app/config.yaml


# # -------------------------------------------
# # CONFIGS & SECRETS
# # -------------------------------------------
        
configs:
  main_config:
    file: ./config.yaml

secrets:
  htpasswd:
    file: ./.htpasswd


