version: '3.3'
services:

# -------------------------------------------
# NODE STACK (add analytical modules here)
# -------------------------------------------
# For compatibility with AHUB, container images
# need to comply with the following:
#   - publish a REST API on port 8000
#   - provide a swagger.json file in the "/" path (if you want to use the GUI)
# -------------------------------------------

  node1:
    image: qunis/ahub_rnode:2.0  # this is a demo container showcasing the R package ahubr

# -------------------------------------------
  
  node2:
    image: qunis/plumberdemo  # this is a demo container showcasing R plumber

# -------------------------------------------
  
  node3:
    image: qunis/prophetdemo  # this is a demo container showcasing Facebook's prophet


# -------------------------------------------
# SERVICE STACK (DO NOT TOUCH)
# -------------------------------------------

  boss:
    image: qunis/ahub_boss:2.0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    configs:
      - source: main_config
        target: /app/config.yaml
    deploy:
      placement:
        constraints: [node.role == manager]


# -------------------------------------------
# CONFIGS & SECRETS
# -------------------------------------------
        
configs:
  main_config:
    file: ./config.yaml

secrets:
  htpasswd:
    file: ./.htpasswd


